services:
  cobranzas-guipak:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
