services:
  cobranzas-guipak:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - dokploy-network

  cobranzas-redis:
    image: redis:7-alpine
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - dokploy-network
    command: redis-server --appendonly yes

volumes:
  redis-data:

networks:
  dokploy-network:
    external: true
